server:
  port: 9004

spring:
  webflux:
    base-path: "/api/catalog-service"
  data:
    mongodb:
      host: localhost
      port: 27017
      username: cp_mongo_user
      password: hoyiAMud5UaZr2y
      database: cp_db
      authentication-database: admin
      autoIndexCreation: true

logging:
  level:
    root: ERROR
    org.course_planner: INFO